using MvvmCross.Commands;
using MvvmCross.Navigation;
using MvvmCross.Plugin.Messenger;
using MvvmCross.ViewModels;
using PlasmaFinder.Models;
using PlasmaFinder.MvxMessages;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace PlasmaFinder.ViewModels
{
    public class SearchItemViewModel : MvxViewModel<string>
    {
        private readonly IMvxNavigationService _mvxNavigationService;
        private readonly IMvxMessenger _mvxMessenger;
        private CancellationTokenSource _throttleCts = new CancellationTokenSource();
        private string _itemType = string.Empty;

        public SearchItemViewModel(IMvxNavigationService mvxNavigationService,
                                       IMvxMessenger mvxMessenger)
        {
            _mvxNavigationService = mvxNavigationService;
            _mvxMessenger = mvxMessenger;
        }

        public override void Prepare(string itemType)
        {
            Items = new ObservableCollection<ListItem>();
            RaisePropertyChanged("Items");
            _itemType = itemType;
        }

        public ObservableCollection<ListItem> Items { get; set; }
        private bool _isBusy = false;
        public bool IsBusy
        {
            get { return _isBusy; }
            set { SetProperty(ref _isBusy, value); }
        }

        private string _itemTypeText = string.Empty;
        public string ItemTypeText
        {
            get { return _itemTypeText; }
            set { SetProperty(ref _itemTypeText, value); }
        }

        public override void ViewAppeared()
        {
            base.ViewAppeared();

            switch (_itemType)
            {
                case "donation":
                    ItemTypeText = "Select Donation Type";
                    BindDonations();
                    break;

                case "cities":
                    ItemTypeText = "Select City";
                    BindCities();
                    break;

                case "states":
                    ItemTypeText = "Select State";
                    BindStates();
                    break;

                case "bloodgroups":
                    ItemTypeText = "Select Blood Group";
                    BindBloodGroups();
                    break;

                default:
                    ItemTypeText = "Select Blood Group";
                    BindBloodGroups();
                    break;
            }        
        }

        public void BindDonations()
        {
            Items = new ObservableCollection<ListItem> {
                new ListItem() { ItemKey = "1", ItemText = "Blood", ItemType = "donationType"},
                new ListItem() { ItemKey = "2", ItemText = "Covid Plasma", ItemType = "donationType"},
                new ListItem() { ItemKey = "3", ItemText = "Food", ItemType = "donationType"},
                new ListItem() { ItemKey = "4", ItemText = "Clothes", ItemType = "donationType"},
                new ListItem() { ItemKey = "", ItemText = "Oxygen", ItemType = "donationType"},
            };
        }

        public void BindStates()
        {
            Items = new ObservableCollection<ListItem> {
                new ListItem() { ItemKey = "1", ItemText = "Andaman & Nicobar [AN]", ItemType = "stateType"},
                new ListItem() { ItemKey = "2", ItemText = "Andhra Pradesh [AP]", ItemType = "stateType"},
                new ListItem() { ItemKey = "3", ItemText = "Arunachal Pradesh [AR]", ItemType = "stateType"},
                new ListItem() { ItemKey = "4", ItemText = "Assam [AS]", ItemType = "stateType"},
                new ListItem() { ItemKey = "5", ItemText = "Bihar [BH]", ItemType = "stateType"},
                new ListItem() { ItemKey = "6", ItemText = "Chandigarh [CH]", ItemType = "stateType"},
                new ListItem() { ItemKey = "7", ItemText = "Chhattisgarh [CG]", ItemType = "stateType"},
                new ListItem() { ItemKey = "8", ItemText = "Dadra & Nagar Haveli [DN]", ItemType = "stateType"},
                new ListItem() { ItemKey = "9", ItemText = "Daman & Diu [DD]", ItemType = "stateType"},
                new ListItem() { ItemKey = "10", ItemText = "Delhi [DL]", ItemType = "stateType"},
                new ListItem() { ItemKey = "11", ItemText = "Goa [GO]", ItemType = "stateType"},
                new ListItem() { ItemKey = "12", ItemText = "Gujarat [GU]", ItemType = "stateType"},
                new ListItem() { ItemKey = "13", ItemText = "Haryana [HR]", ItemType = "stateType"},
                new ListItem() { ItemKey = "14", ItemText = "Himachal Pradesh [HP]", ItemType = "stateType"},
                new ListItem() { ItemKey = "15", ItemText = "Jammu & Kashmir [JK]", ItemType = "stateType"},
                new ListItem() { ItemKey = "16", ItemText = "Jharkhand [JH]", ItemType = "stateType"},
                new ListItem() { ItemKey = "17", ItemText = "Karnataka [KR]", ItemType = "stateType"},
                new ListItem() { ItemKey = "18", ItemText = "Kerala [KL]", ItemType = "stateType"},
                new ListItem() { ItemKey = "19", ItemText = "Lakshadweep [LD]", ItemType = "stateType"},
                new ListItem() { ItemKey = "20", ItemText = "Madhya Pradesh [MP]", ItemType = "stateType"},
                new ListItem() { ItemKey = "21", ItemText = "Maharashtra [MH]", ItemType = "stateType"},
                new ListItem() { ItemKey = "22", ItemText = "Manipur [MN]", ItemType = "stateType"},
                new ListItem() { ItemKey = "23", ItemText = "Meghalaya [ML]", ItemType = "stateType"},
                new ListItem() { ItemKey = "24", ItemText = "Mizoram [MM]", ItemType = "stateType"},
                new ListItem() { ItemKey = "25", ItemText = "Nagaland [NL]", ItemType = "stateType"},
                new ListItem() { ItemKey = "26", ItemText = "Orissa [OR]", ItemType = "stateType"},
                new ListItem() { ItemKey = "27", ItemText = "Pondicherry [PC]", ItemType = "stateType"},
                new ListItem() { ItemKey = "28", ItemText = "Punjab [PJ]", ItemType = "stateType"},
                new ListItem() { ItemKey = "29", ItemText = "Rajasthan [RJ]", ItemType = "stateType"},
                new ListItem() { ItemKey = "30", ItemText = "Sikkim [SK]", ItemType = "stateType"},
                new ListItem() { ItemKey = "31", ItemText = "Tamil Nadu [TN]", ItemType = "stateType"},
                new ListItem() { ItemKey = "32", ItemText = "Tripura [TR]", ItemType = "stateType"},
                new ListItem() { ItemKey = "33", ItemText = "Uttar Pradesh [UP]", ItemType = "stateType"},
                new ListItem() { ItemKey = "34", ItemText = "Uttaranchal [UT]", ItemType = "stateType"},
                new ListItem() { ItemKey = "35", ItemText = "West Bengal [WB]", ItemType = "stateType"},
            };
        }

        public void BindCities()
        {
            Items = new ObservableCollection<ListItem> {
            new ListItem() { ParentTypeId="1", ItemKey = "101", ItemText = "Alipur", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "102", ItemText = "Andaman Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "103", ItemText = "Anderson Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "104", ItemText = "Arainj-Laka-Punga", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "105", ItemText = "Austinabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "106", ItemText = "Bamboo Flat", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "107", ItemText = "Barren Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "108", ItemText = "Beadonabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "109", ItemText = "Betapur", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "110", ItemText = "Bindraban", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "111", ItemText = "Bonington", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "112", ItemText = "Brookesabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "113", ItemText = "Cadell Point", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "114", ItemText = "Calicut", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "115", ItemText = "Chetamale", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "116", ItemText = "Cinque Islands", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "117", ItemText = "Defence Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "118", ItemText = "Digilpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "119", ItemText = "Dolyganj", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "120", ItemText = "Flat Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "121", ItemText = "Geinyale", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "122", ItemText = "Great Coco Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "123", ItemText = "Haddo", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "124", ItemText = "Havelock Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "125", ItemText = "Henry Lawrence Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "126", ItemText = "Herbertabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "127", ItemText = "Hobdaypur", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "128", ItemText = "Ilichar", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "128", ItemText = "Ingoie", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "130", ItemText = "Inteview Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "131", ItemText = "Jangli Ghat", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "132", ItemText = "Jhon Lawrence Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "133", ItemText = "Karen", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "134", ItemText = "Kartara", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "135", ItemText = "KYD Islannd", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "136", ItemText = "Landfall Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "137", ItemText = "Little Andmand", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "138", ItemText = "Little Coco Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "138", ItemText = "Long Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "140", ItemText = "Maimyo", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "141", ItemText = "Malappuram", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "142", ItemText = "Manglutan", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "143", ItemText = "Manpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "144", ItemText = "Mitha Khari", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "145", ItemText = "Neill Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "146", ItemText = "Nicobar Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "147", ItemText = "North Brother Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "148", ItemText = "North Passage Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "149", ItemText = "North Sentinel Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "150", ItemText = "Nothen Reef Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "151", ItemText = "Outram Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "152", ItemText = "Pahlagaon", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "153", ItemText = "Palalankwe", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "154", ItemText = "Passage Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "155", ItemText = "Phaiapong", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "156", ItemText = "Phoenix Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "157", ItemText = "Port Blair", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "158", ItemText = "Preparis Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "159", ItemText = "Protheroepur", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "160", ItemText = "Rangachang", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "161", ItemText = "Rongat", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "162", ItemText = "Rutland Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "163", ItemText = "Sabari", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "164", ItemText = "Saddle Peak", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "165", ItemText = "Shadipur", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "166", ItemText = "Smith Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "167", ItemText = "Sound Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "168", ItemText = "South Sentinel Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "169", ItemText = "Spike Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "170", ItemText = "Tarmugli Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "171", ItemText = "Taylerabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "172", ItemText = "Titaije", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "173", ItemText = "Toibalawe", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "174", ItemText = "Tusonabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "175", ItemText = "West Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "176", ItemText = "Wimberleyganj", ItemType = "cityType"},
new ListItem() { ParentTypeId="1", ItemKey = "177", ItemText = "Yadita", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "201", ItemText = "Adilabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "201", ItemText = "Anantapur", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "203", ItemText = "Chittoor", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "204", ItemText = "Cuddapah", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "205", ItemText = "East Godavari", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "206", ItemText = "Guntur", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "207", ItemText = "Hyderabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "208", ItemText = "Karimnagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "209", ItemText = "Khammam", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "210", ItemText = "Krishna", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "211", ItemText = "Kurnool", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "212", ItemText = "Mahabubnagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "213", ItemText = "Medak", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "214", ItemText = "Nalgonda", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "215", ItemText = "Nellore", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "216", ItemText = "Nizamabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "217", ItemText = "Prakasam", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "218", ItemText = "Rangareddy", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "219", ItemText = "Srikakulam", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "220", ItemText = "Visakhapatnam", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "221", ItemText = "Vizianagaram", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "222", ItemText = "Warangal", ItemType = "cityType"},
new ListItem() { ParentTypeId="2", ItemKey = "223", ItemText = "West Godavari", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "301", ItemText = "Anjaw", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "302", ItemText = "Changlang", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "303", ItemText = "Dibang Valley", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "304", ItemText = "East Kameng", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "305", ItemText = "East Siang", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "306", ItemText = "Itanagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "307", ItemText = "Kurung Kumey", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "308", ItemText = "Lohit", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "309", ItemText = "Lower Dibang Valley", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "310", ItemText = "Lower Subansiri", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "311", ItemText = "Papum Pare", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "312", ItemText = "Tawang", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "313", ItemText = "Tirap", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "314", ItemText = "Upper Siang", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "315", ItemText = "Upper Subansiri", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "316", ItemText = "West Kameng", ItemType = "cityType"},
new ListItem() { ParentTypeId="3", ItemKey = "317", ItemText = "West Siang", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "401", ItemText = "Barpeta", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "402", ItemText = "Bongaigaon", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "403", ItemText = "Cachar", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "404", ItemText = "Darrang", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "405", ItemText = "Dhemaji", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "406", ItemText = "Dhubri", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "407", ItemText = "Dibrugarh", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "408", ItemText = "Goalpara", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "409", ItemText = "Golaghat", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "410", ItemText = "Guwahati", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "411", ItemText = "Hailakandi", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "412", ItemText = "Jorhat", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "413", ItemText = "Kamrup", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "414", ItemText = "Karbi Anglong", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "415", ItemText = "Karimganj", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "416", ItemText = "Kokrajhar", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "417", ItemText = "Lakhimpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "418", ItemText = "Marigaon", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "419", ItemText = "Nagaon", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "420", ItemText = "Nalbari", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "421", ItemText = "North Cachar Hills", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "422", ItemText = "Silchar", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "423", ItemText = "Sivasagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "424", ItemText = "Sonitpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "425", ItemText = "Tinsukia", ItemType = "cityType"},
new ListItem() { ParentTypeId="4", ItemKey = "426", ItemText = "Udalguri", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "501", ItemText = "Araria", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "502", ItemText = "Aurangabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "503", ItemText = "Banka", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "504", ItemText = "Begusarai", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "505", ItemText = "Bhagalpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "506", ItemText = "Bhojpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "507", ItemText = "Buxar", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "508", ItemText = "Darbhanga", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "509", ItemText = "East Champaran", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "510", ItemText = "Gaya", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "511", ItemText = "Gopalganj", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "512", ItemText = "Jamshedpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "513", ItemText = "Jamui", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "514", ItemText = "Jehanabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "515", ItemText = "Kaimur (Bhabua)", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "516", ItemText = "Katihar", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "517", ItemText = "Khagaria", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "518", ItemText = "Kishanganj", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "519", ItemText = "Lakhisarai", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "520", ItemText = "Madhepura", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "521", ItemText = "Madhubani", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "522", ItemText = "Munger", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "523", ItemText = "Muzaffarpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "524", ItemText = "Nalanda", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "525", ItemText = "Nawada", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "526", ItemText = "Patna", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "527", ItemText = "Purnia", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "528", ItemText = "Rohtas", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "529", ItemText = "Saharsa", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "530", ItemText = "Samastipur", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "531", ItemText = "Saran", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "532", ItemText = "Sheikhpura", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "533", ItemText = "Sheohar", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "534", ItemText = "Sitamarhi", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "535", ItemText = "Siwan", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "536", ItemText = "Supaul", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "537", ItemText = "Vaishali", ItemType = "cityType"},
new ListItem() { ParentTypeId="5", ItemKey = "538", ItemText = "West Champaran", ItemType = "cityType"},
new ListItem() { ParentTypeId="6", ItemKey = "601", ItemText = "Chandigarh", ItemType = "cityType"},
new ListItem() { ParentTypeId="6", ItemKey = "602", ItemText = "Mani Marja", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "701", ItemText = "Bastar", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "702", ItemText = "Bhilai", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "703", ItemText = "Bijapur", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "704", ItemText = "Bilaspur", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "705", ItemText = "Dhamtari", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "706", ItemText = "Durg", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "707", ItemText = "Janjgir-Champa", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "708", ItemText = "Jashpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "709", ItemText = "Kabirdham-Kawardha", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "710", ItemText = "Korba", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "711", ItemText = "Korea", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "712", ItemText = "Mahasamund", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "713", ItemText = "Narayanpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "714", ItemText = "Norh Bastar-Kanker", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "715", ItemText = "Raigarh", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "716", ItemText = "Raipur", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "717", ItemText = "Rajnandgaon", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "718", ItemText = "South Bastar-Dantewada", ItemType = "cityType"},
new ListItem() { ParentTypeId="7", ItemKey = "719", ItemText = "Surguja", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "801", ItemText = "Amal", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "802", ItemText = "Amli", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "803", ItemText = "Bedpa", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "804", ItemText = "Chikhli", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "805", ItemText = "Dadra & Nagar Haveli", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "806", ItemText = "Dahikhed", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "807", ItemText = "Dolara", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "808", ItemText = "Galonda", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "809", ItemText = "Kanadi", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "810", ItemText = "Karchond", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "811", ItemText = "Khadoli", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "812", ItemText = "Kharadpada", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "813", ItemText = "Kherabari", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "814", ItemText = "Kherdi", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "815", ItemText = "Kothar", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "816", ItemText = "Luari", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "817", ItemText = "Mashat", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "818", ItemText = "Rakholi", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "819", ItemText = "Rudana", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "820", ItemText = "Saili", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "821", ItemText = "Sili", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "822", ItemText = "Silvassa", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "823", ItemText = "Sindavni", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "824", ItemText = "Udva", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "825", ItemText = "Umbarkoi", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "826", ItemText = "Vansda", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "827", ItemText = "Vasona", ItemType = "cityType"},
new ListItem() { ParentTypeId="8", ItemKey = "828", ItemText = "Velugam", ItemType = "cityType"},
new ListItem() { ParentTypeId="9", ItemKey = "901", ItemText = "Brancavare", ItemType = "cityType"},
new ListItem() { ParentTypeId="9", ItemKey = "902", ItemText = "Dagasi", ItemType = "cityType"},
new ListItem() { ParentTypeId="9", ItemKey = "903", ItemText = "Daman", ItemType = "cityType"},
new ListItem() { ParentTypeId="9", ItemKey = "904", ItemText = "Diu", ItemType = "cityType"},
new ListItem() { ParentTypeId="9", ItemKey = "905", ItemText = "Magarvara", ItemType = "cityType"},
new ListItem() { ParentTypeId="9", ItemKey = "906", ItemText = "Nagwa", ItemType = "cityType"},
new ListItem() { ParentTypeId="9", ItemKey = "907", ItemText = "Pariali", ItemType = "cityType"},
new ListItem() { ParentTypeId="9", ItemKey = "908", ItemText = "Passo Covo", ItemType = "cityType"},
new ListItem() { ParentTypeId="10", ItemKey = "1001", ItemText = "Central Delhi", ItemType = "cityType"},
new ListItem() { ParentTypeId="10", ItemKey = "1002", ItemText = "East Delhi", ItemType = "cityType"},
new ListItem() { ParentTypeId="10", ItemKey = "1003", ItemText = "New Delhi", ItemType = "cityType"},
new ListItem() { ParentTypeId="10", ItemKey = "1004", ItemText = "North Delhi", ItemType = "cityType"},
new ListItem() { ParentTypeId="10", ItemKey = "1005", ItemText = "North East Delhi", ItemType = "cityType"},
new ListItem() { ParentTypeId="10", ItemKey = "1006", ItemText = "North West Delhi", ItemType = "cityType"},
new ListItem() { ParentTypeId="10", ItemKey = "1007", ItemText = "Old Delhi", ItemType = "cityType"},
new ListItem() { ParentTypeId="10", ItemKey = "1008", ItemText = "South Delhi", ItemType = "cityType"},
new ListItem() { ParentTypeId="10", ItemKey = "1009", ItemText = "South West Delhi", ItemType = "cityType"},
new ListItem() { ParentTypeId="10", ItemKey = "1010", ItemText = "West Delhi", ItemType = "cityType"},
new ListItem() { ParentTypeId="11", ItemKey = "1101", ItemText = "Canacona", ItemType = "cityType"},
new ListItem() { ParentTypeId="11", ItemKey = "1102", ItemText = "Candolim", ItemType = "cityType"},
new ListItem() { ParentTypeId="11", ItemKey = "1103", ItemText = "Chinchinim", ItemType = "cityType"},
new ListItem() { ParentTypeId="11", ItemKey = "1104", ItemText = "Cortalim", ItemType = "cityType"},
new ListItem() { ParentTypeId="11", ItemKey = "1105", ItemText = "Goa", ItemType = "cityType"},
new ListItem() { ParentTypeId="11", ItemKey = "1106", ItemText = "Jua", ItemType = "cityType"},
new ListItem() { ParentTypeId="11", ItemKey = "1107", ItemText = "Madgaon", ItemType = "cityType"},
new ListItem() { ParentTypeId="11", ItemKey = "1108", ItemText = "Mahem", ItemType = "cityType"},
new ListItem() { ParentTypeId="11", ItemKey = "1109", ItemText = "Mapuca", ItemType = "cityType"},
new ListItem() { ParentTypeId="11", ItemKey = "1110", ItemText = "Marmagao", ItemType = "cityType"},
new ListItem() { ParentTypeId="11", ItemKey = "1111", ItemText = "Panji", ItemType = "cityType"},
new ListItem() { ParentTypeId="11", ItemKey = "1112", ItemText = "Ponda", ItemType = "cityType"},
new ListItem() { ParentTypeId="11", ItemKey = "1113", ItemText = "Sanvordem", ItemType = "cityType"},
new ListItem() { ParentTypeId="11", ItemKey = "1114", ItemText = "Terekhol", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1201", ItemText = "Ahmedabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1202", ItemText = "Amreli", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1203", ItemText = "Anand", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1204", ItemText = "Banaskantha", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1205", ItemText = "Baroda", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1206", ItemText = "Bharuch", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1207", ItemText = "Bhavnagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1208", ItemText = "Dahod", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1209", ItemText = "Dang", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1210", ItemText = "Dwarka", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1211", ItemText = "Gandhinagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1212", ItemText = "Jamnagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1213", ItemText = "Junagadh", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1214", ItemText = "Kheda", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1215", ItemText = "Kutch", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1216", ItemText = "Mehsana", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1217", ItemText = "Nadiad", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1218", ItemText = "Narmada", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1219", ItemText = "Navsari", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1220", ItemText = "Panchmahals", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1221", ItemText = "Patan", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1222", ItemText = "Porbandar", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1223", ItemText = "Rajkot", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1224", ItemText = "Sabarkantha", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1225", ItemText = "Surat", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1226", ItemText = "Surendranagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1227", ItemText = "Vadodara", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1228", ItemText = "Valsad", ItemType = "cityType"},
new ListItem() { ParentTypeId="12", ItemKey = "1229", ItemText = "Vapi", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1301", ItemText = "Ambala", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1302", ItemText = "Bhiwani", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1303", ItemText = "Faridabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1304", ItemText = "Fatehabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1305", ItemText = "Gurgaon", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1306", ItemText = "Hisar", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1307", ItemText = "Jhajjar", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1308", ItemText = "Jind", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1309", ItemText = "Kaithal", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1310", ItemText = "Karnal", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1311", ItemText = "Kurukshetra", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1312", ItemText = "Mahendragarh", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1313", ItemText = "Mewat", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1314", ItemText = "Panchkula", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1315", ItemText = "Panipat", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1316", ItemText = "Rewari", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1317", ItemText = "Rohtak", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1318", ItemText = "Sirsa", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1319", ItemText = "Sonipat", ItemType = "cityType"},
new ListItem() { ParentTypeId="13", ItemKey = "1320", ItemText = "Yamunanagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="14", ItemKey = "1401", ItemText = "Bilaspur", ItemType = "cityType"},
new ListItem() { ParentTypeId="14", ItemKey = "1402", ItemText = "Chamba", ItemType = "cityType"},
new ListItem() { ParentTypeId="14", ItemKey = "1403", ItemText = "Dalhousie", ItemType = "cityType"},
new ListItem() { ParentTypeId="14", ItemKey = "1404", ItemText = "Hamirpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="14", ItemKey = "1405", ItemText = "Kangra", ItemType = "cityType"},
new ListItem() { ParentTypeId="14", ItemKey = "1406", ItemText = "Kinnaur", ItemType = "cityType"},
new ListItem() { ParentTypeId="14", ItemKey = "1407", ItemText = "Kullu", ItemType = "cityType"},
new ListItem() { ParentTypeId="14", ItemKey = "1408", ItemText = "Lahaul & Spiti", ItemType = "cityType"},
new ListItem() { ParentTypeId="14", ItemKey = "1409", ItemText = "Mandi", ItemType = "cityType"},
new ListItem() { ParentTypeId="14", ItemKey = "1410", ItemText = "Shimla", ItemType = "cityType"},
new ListItem() { ParentTypeId="14", ItemKey = "1411", ItemText = "Sirmaur", ItemType = "cityType"},
new ListItem() { ParentTypeId="14", ItemKey = "1412", ItemText = "Solan", ItemType = "cityType"},
new ListItem() { ParentTypeId="14", ItemKey = "1413", ItemText = "Una", ItemType = "cityType"},
new ListItem() { ParentTypeId="15", ItemKey = "1501", ItemText = "Anantnag", ItemType = "cityType"},
new ListItem() { ParentTypeId="15", ItemKey = "1502", ItemText = "Baramulla", ItemType = "cityType"},
new ListItem() { ParentTypeId="15", ItemKey = "1503", ItemText = "Budgam", ItemType = "cityType"},
new ListItem() { ParentTypeId="15", ItemKey = "1504", ItemText = "Doda", ItemType = "cityType"},
new ListItem() { ParentTypeId="15", ItemKey = "1505", ItemText = "Jammu", ItemType = "cityType"},
new ListItem() { ParentTypeId="15", ItemKey = "1506", ItemText = "Kargil", ItemType = "cityType"},
new ListItem() { ParentTypeId="15", ItemKey = "1507", ItemText = "Kathua", ItemType = "cityType"},
new ListItem() { ParentTypeId="15", ItemKey = "1508", ItemText = "Kupwara", ItemType = "cityType"},
new ListItem() { ParentTypeId="15", ItemKey = "1509", ItemText = "Leh", ItemType = "cityType"},
new ListItem() { ParentTypeId="15", ItemKey = "1510", ItemText = "Poonch", ItemType = "cityType"},
new ListItem() { ParentTypeId="15", ItemKey = "1511", ItemText = "Pulwama", ItemType = "cityType"},
new ListItem() { ParentTypeId="15", ItemKey = "1512", ItemText = "Rajauri", ItemType = "cityType"},
new ListItem() { ParentTypeId="15", ItemKey = "1513", ItemText = "Srinagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="15", ItemKey = "1514", ItemText = "Udhampur", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1601", ItemText = "Bokaro", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1602", ItemText = "Chatra", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1603", ItemText = "Deoghar", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1604", ItemText = "Dhanbad", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1605", ItemText = "Dumka", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1606", ItemText = "East Singhbhum", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1607", ItemText = "Garhwa", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1608", ItemText = "Giridih", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1609", ItemText = "Godda", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1610", ItemText = "Gumla", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1611", ItemText = "Hazaribag", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1612", ItemText = "Jamtara", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1613", ItemText = "Koderma", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1614", ItemText = "Latehar", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1615", ItemText = "Lohardaga", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1616", ItemText = "Pakur", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1617", ItemText = "Palamu", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1618", ItemText = "Ranchi", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1619", ItemText = "Sahibganj", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1620", ItemText = "Seraikela", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1621", ItemText = "Simdega", ItemType = "cityType"},
new ListItem() { ParentTypeId="16", ItemKey = "1622", ItemText = "West Singhbhum", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1701", ItemText = "Bagalkot", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1702", ItemText = "Bangalore", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1703", ItemText = "Bangalore Rural", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1704", ItemText = "Belgaum", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1705", ItemText = "Bellary", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1706", ItemText = "Bhatkal", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1707", ItemText = "Bidar", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1708", ItemText = "Bijapur", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1709", ItemText = "Chamrajnagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1710", ItemText = "Chickmagalur", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1711", ItemText = "Chikballapur", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1712", ItemText = "Chitradurga", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1713", ItemText = "Dakshina Kannada", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1714", ItemText = "Davanagere", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1715", ItemText = "Dharwad", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1716", ItemText = "Gadag", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1717", ItemText = "Gulbarga", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1718", ItemText = "Hampi", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1719", ItemText = "Hassan", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1720", ItemText = "Haveri", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1721", ItemText = "Hospet", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1722", ItemText = "Karwar", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1723", ItemText = "Kodagu", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1724", ItemText = "Kolar", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1725", ItemText = "Koppal", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1726", ItemText = "Madikeri", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1727", ItemText = "Mandya", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1728", ItemText = "Mangalore", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1729", ItemText = "Manipal", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1730", ItemText = "Mysore", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1731", ItemText = "Raichur", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1732", ItemText = "Shimoga", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1733", ItemText = "Sirsi", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1734", ItemText = "Sringeri", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1735", ItemText = "Srirangapatna", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1736", ItemText = "Tumkur", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1737", ItemText = "Udupi", ItemType = "cityType"},
new ListItem() { ParentTypeId="17", ItemKey = "1738", ItemText = "Uttara Kannada", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1801", ItemText = "Alappuzha", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1802", ItemText = "Alleppey", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1803", ItemText = "Alwaye", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1804", ItemText = "Ernakulam", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1805", ItemText = "Idukki", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1806", ItemText = "Kannur", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1807", ItemText = "Kasargod", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1808", ItemText = "Kochi", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1809", ItemText = "Kollam", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1810", ItemText = "Kottayam", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1811", ItemText = "Kovalam", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1812", ItemText = "Kozhikode", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1813", ItemText = "Malappuram", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1814", ItemText = "Palakkad", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1815", ItemText = "Pathanamthitta", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1816", ItemText = "Perumbavoor", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1817", ItemText = "Thiruvananthapuram", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1818", ItemText = "Thrissur", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1819", ItemText = "Trichur", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1820", ItemText = "Trivandrum", ItemType = "cityType"},
new ListItem() { ParentTypeId="18", ItemKey = "1821", ItemText = "Wayanad", ItemType = "cityType"},
new ListItem() { ParentTypeId="19", ItemKey = "1901", ItemText = "Agatti Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="19", ItemKey = "1902", ItemText = "Bingaram Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="19", ItemKey = "1903", ItemText = "Bitra Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="19", ItemKey = "1904", ItemText = "Chetlat Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="19", ItemKey = "1905", ItemText = "Kadmat Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="19", ItemKey = "1906", ItemText = "Kalpeni Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="19", ItemKey = "1907", ItemText = "Kavaratti Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="19", ItemKey = "1908", ItemText = "Kiltan Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="19", ItemKey = "1909", ItemText = "Lakshadweep Sea", ItemType = "cityType"},
new ListItem() { ParentTypeId="19", ItemKey = "1910", ItemText = "Minicoy Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="19", ItemKey = "1911", ItemText = "North Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="19", ItemKey = "1912", ItemText = "South Island", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2001", ItemText = "Anuppur", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2002", ItemText = "Ashoknagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2003", ItemText = "Balaghat", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2004", ItemText = "Barwani", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2005", ItemText = "Betul", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2006", ItemText = "Bhind", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2007", ItemText = "Bhopal", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2008", ItemText = "Burhanpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2009", ItemText = "Chhatarpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2010", ItemText = "Chhindwara", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2011", ItemText = "Damoh", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2012", ItemText = "Datia", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2013", ItemText = "Dewas", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2014", ItemText = "Dhar", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2015", ItemText = "Dindori", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2016", ItemText = "Guna", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2017", ItemText = "Gwalior", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2018", ItemText = "Harda", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2019", ItemText = "Hoshangabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2020", ItemText = "Indore", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2021", ItemText = "Jabalpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2022", ItemText = "Jagdalpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2023", ItemText = "Jhabua", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2024", ItemText = "Katni", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2025", ItemText = "Khandwa", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2026", ItemText = "Khargone", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2027", ItemText = "Mandla", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2028", ItemText = "Mandsaur", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2029", ItemText = "Morena", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2030", ItemText = "Narsinghpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2031", ItemText = "Neemuch", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2032", ItemText = "Panna", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2033", ItemText = "Raisen", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2034", ItemText = "Rajgarh", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2035", ItemText = "Ratlam", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2036", ItemText = "Rewa", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2037", ItemText = "Sagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2038", ItemText = "Satna", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2039", ItemText = "Sehore", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2040", ItemText = "Seoni", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2041", ItemText = "Shahdol", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2042", ItemText = "Shajapur", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2043", ItemText = "Sheopur", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2044", ItemText = "Shivpuri", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2045", ItemText = "Sidhi", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2046", ItemText = "Tikamgarh", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2047", ItemText = "Ujjain", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2048", ItemText = "Umaria", ItemType = "cityType"},
new ListItem() { ParentTypeId="20", ItemKey = "2049", ItemText = "Vidisha", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2101", ItemText = "Ahmednagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2102", ItemText = "Akola", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2103", ItemText = "Amravati", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2104", ItemText = "Aurangabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2105", ItemText = "Beed", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2106", ItemText = "Bhandara", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2107", ItemText = "Buldhana", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2108", ItemText = "Chandrapur", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2109", ItemText = "Dhule", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2110", ItemText = "Gadchiroli", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2111", ItemText = "Gondia", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2112", ItemText = "Hingoli", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2113", ItemText = "Jalgaon", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2114", ItemText = "Jalna", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2115", ItemText = "Kolhapur", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2116", ItemText = "Latur", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2117", ItemText = "Mahabaleshwar", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2118", ItemText = "Mumbai", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2119", ItemText = "Mumbai City", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2120", ItemText = "Mumbai Suburban", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2121", ItemText = "Nagpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2122", ItemText = "Nanded", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2123", ItemText = "Nandurbar", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2124", ItemText = "Nashik", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2125", ItemText = "Osmanabad", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2126", ItemText = "Parbhani", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2127", ItemText = "Pune", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2128", ItemText = "Raigad", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2129", ItemText = "Ratnagiri", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2130", ItemText = "Sangli", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2131", ItemText = "Satara", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2132", ItemText = "Sholapur", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2133", ItemText = "Sindhudurg", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2134", ItemText = "Thane", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2135", ItemText = "Wardha", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2136", ItemText = "Washim", ItemType = "cityType"},
new ListItem() { ParentTypeId="21", ItemKey = "2137", ItemText = "Yavatmal", ItemType = "cityType"},
new ListItem() { ParentTypeId="22", ItemKey = "2201", ItemText = "Bishnupur", ItemType = "cityType"},
new ListItem() { ParentTypeId="22", ItemKey = "2202", ItemText = "Chandel", ItemType = "cityType"},
new ListItem() { ParentTypeId="22", ItemKey = "2203", ItemText = "Churachandpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="22", ItemKey = "2204", ItemText = "Imphal East", ItemType = "cityType"},
new ListItem() { ParentTypeId="22", ItemKey = "2205", ItemText = "Imphal West", ItemType = "cityType"},
new ListItem() { ParentTypeId="22", ItemKey = "2206", ItemText = "Senapati", ItemType = "cityType"},
new ListItem() { ParentTypeId="22", ItemKey = "2207", ItemText = "Tamenglong", ItemType = "cityType"},
new ListItem() { ParentTypeId="22", ItemKey = "2208", ItemText = "Thoubal", ItemType = "cityType"},
new ListItem() { ParentTypeId="22", ItemKey = "2209", ItemText = "Ukhrul", ItemType = "cityType"},
new ListItem() { ParentTypeId="23", ItemKey = "2301", ItemText = "East Garo Hills", ItemType = "cityType"},
new ListItem() { ParentTypeId="23", ItemKey = "2302", ItemText = "East Khasi Hills", ItemType = "cityType"},
new ListItem() { ParentTypeId="23", ItemKey = "2303", ItemText = "Jaintia Hills", ItemType = "cityType"},
new ListItem() { ParentTypeId="23", ItemKey = "2304", ItemText = "Ri Bhoi", ItemType = "cityType"},
new ListItem() { ParentTypeId="23", ItemKey = "2305", ItemText = "Shillong", ItemType = "cityType"},
new ListItem() { ParentTypeId="23", ItemKey = "2306", ItemText = "South Garo Hills", ItemType = "cityType"},
new ListItem() { ParentTypeId="23", ItemKey = "2307", ItemText = "West Garo Hills", ItemType = "cityType"},
new ListItem() { ParentTypeId="23", ItemKey = "2308", ItemText = "West Khasi Hills", ItemType = "cityType"},
new ListItem() { ParentTypeId="24", ItemKey = "2401", ItemText = "Aizawl", ItemType = "cityType"},
new ListItem() { ParentTypeId="24", ItemKey = "2402", ItemText = "Champhai", ItemType = "cityType"},
new ListItem() { ParentTypeId="24", ItemKey = "2403", ItemText = "Kolasib", ItemType = "cityType"},
new ListItem() { ParentTypeId="24", ItemKey = "2404", ItemText = "Lawngtlai", ItemType = "cityType"},
new ListItem() { ParentTypeId="24", ItemKey = "2405", ItemText = "Lunglei", ItemType = "cityType"},
new ListItem() { ParentTypeId="24", ItemKey = "2406", ItemText = "Mamit", ItemType = "cityType"},
new ListItem() { ParentTypeId="24", ItemKey = "2407", ItemText = "Saiha", ItemType = "cityType"},
new ListItem() { ParentTypeId="24", ItemKey = "2408", ItemText = "Serchhip", ItemType = "cityType"},
new ListItem() { ParentTypeId="25", ItemKey = "2501", ItemText = "Dimapur", ItemType = "cityType"},
new ListItem() { ParentTypeId="25", ItemKey = "2502", ItemText = "Kohima", ItemType = "cityType"},
new ListItem() { ParentTypeId="25", ItemKey = "2503", ItemText = "Mokokchung", ItemType = "cityType"},
new ListItem() { ParentTypeId="25", ItemKey = "2504", ItemText = "Mon", ItemType = "cityType"},
new ListItem() { ParentTypeId="25", ItemKey = "2505", ItemText = "Phek", ItemType = "cityType"},
new ListItem() { ParentTypeId="25", ItemKey = "2506", ItemText = "Tuensang", ItemType = "cityType"},
new ListItem() { ParentTypeId="25", ItemKey = "2507", ItemText = "Wokha", ItemType = "cityType"},
new ListItem() { ParentTypeId="25", ItemKey = "2508", ItemText = "Zunheboto", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2601", ItemText = "Angul", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2602", ItemText = "Balangir", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2603", ItemText = "Balasore", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2604", ItemText = "Baleswar", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2605", ItemText = "Bargarh", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2606", ItemText = "Berhampur", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2607", ItemText = "Bhadrak", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2608", ItemText = "Bhubaneswar", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2609", ItemText = "Boudh", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2610", ItemText = "Cuttack", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2611", ItemText = "Deogarh", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2612", ItemText = "Dhenkanal", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2613", ItemText = "Gajapati", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2614", ItemText = "Ganjam", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2615", ItemText = "Jagatsinghapur", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2616", ItemText = "Jajpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2617", ItemText = "Jharsuguda", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2618", ItemText = "Kalahandi", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2619", ItemText = "Kandhamal", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2620", ItemText = "Kendrapara", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2621", ItemText = "Kendujhar", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2622", ItemText = "Khordha", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2623", ItemText = "Koraput", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2624", ItemText = "Malkangiri", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2625", ItemText = "Mayurbhanj", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2626", ItemText = "Nabarangapur", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2627", ItemText = "Nayagarh", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2628", ItemText = "Nuapada", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2629", ItemText = "Puri", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2630", ItemText = "Rayagada", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2631", ItemText = "Rourkela", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2632", ItemText = "Sambalpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2633", ItemText = "Subarnapur", ItemType = "cityType"},
new ListItem() { ParentTypeId="26", ItemKey = "2634", ItemText = "Sundergarh", ItemType = "cityType"},
new ListItem() { ParentTypeId="27", ItemKey = "2701", ItemText = "Bahur", ItemType = "cityType"},
new ListItem() { ParentTypeId="27", ItemKey = "2701", ItemText = "Karaikal", ItemType = "cityType"},
new ListItem() { ParentTypeId="27", ItemKey = "2701", ItemText = "Mahe", ItemType = "cityType"},
new ListItem() { ParentTypeId="27", ItemKey = "2701", ItemText = "Pondicherry", ItemType = "cityType"},
new ListItem() { ParentTypeId="27", ItemKey = "2701", ItemText = "Purnankuppam", ItemType = "cityType"},
new ListItem() { ParentTypeId="27", ItemKey = "2701", ItemText = "Valudavur", ItemType = "cityType"},
new ListItem() { ParentTypeId="27", ItemKey = "2701", ItemText = "Villianur", ItemType = "cityType"},
new ListItem() { ParentTypeId="27", ItemKey = "2701", ItemText = "Yanam", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Amritsar", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Barnala", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Bathinda", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Faridkot", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Fatehgarh Sahib", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Ferozepur", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Gurdaspur", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Hoshiarpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Jalandhar", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Kapurthala", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Ludhiana", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Mansa", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Moga", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Muktsar", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Nawanshahr", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Pathankot", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Patiala", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Rupnagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Sangrur", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "SAS Nagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="28", ItemKey = "2801", ItemText = "Tarn Taran", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2901", ItemText = "Ajmer", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2902", ItemText = "Alwar", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2903", ItemText = "Banswara", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2904", ItemText = "Baran", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2905", ItemText = "Barmer", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2906", ItemText = "Bharatpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2907", ItemText = "Bhilwara", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2908", ItemText = "Bikaner", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2909", ItemText = "Bundi", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2910", ItemText = "Chittorgarh", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2911", ItemText = "Churu", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2912", ItemText = "Dausa", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2913", ItemText = "Dholpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2914", ItemText = "Dungarpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2915", ItemText = "Hanumangarh", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2916", ItemText = "Jaipur", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2917", ItemText = "Jaisalmer", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2918", ItemText = "Jalore", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2919", ItemText = "Jhalawar", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2920", ItemText = "Jhunjhunu", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2921", ItemText = "Jodhpur", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2922", ItemText = "Karauli", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2923", ItemText = "Kota", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2924", ItemText = "Nagaur", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2925", ItemText = "Pali", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2926", ItemText = "Pilani", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2927", ItemText = "Rajsamand", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2928", ItemText = "Sawai Madhopur", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2929", ItemText = "Sikar", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2930", ItemText = "Sirohi", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2931", ItemText = "Sri Ganganagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2932", ItemText = "Tonk", ItemType = "cityType"},
new ListItem() { ParentTypeId="29", ItemKey = "2933", ItemText = "Udaipur", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3001", ItemText = "Barmiak", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3002", ItemText = "Be", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3003", ItemText = "Bhurtuk", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3004", ItemText = "Chhubakha", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3005", ItemText = "Chidam", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3006", ItemText = "Chubha", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3007", ItemText = "Chumikteng", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3008", ItemText = "Dentam", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3009", ItemText = "Dikchu", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3010", ItemText = "Dzongri", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3011", ItemText = "Gangtok", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3012", ItemText = "Gauzing", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3013", ItemText = "Gyalshing", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3014", ItemText = "Hema", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3015", ItemText = "Kerung", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3016", ItemText = "Lachen", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3017", ItemText = "Lachung", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3018", ItemText = "Lema", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3019", ItemText = "Lingtam", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3020", ItemText = "Lungthu", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3021", ItemText = "Mangan", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3022", ItemText = "Namchi", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3023", ItemText = "Namthang", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3024", ItemText = "Nanga", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3025", ItemText = "Nantang", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3026", ItemText = "Naya Bazar", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3027", ItemText = "Padamachen", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3028", ItemText = "Pakhyong", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3029", ItemText = "Pemayangtse", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3030", ItemText = "Phensang", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3031", ItemText = "Rangli", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3032", ItemText = "Rinchingpong", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3033", ItemText = "Sakyong", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3034", ItemText = "Samdong", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3035", ItemText = "Singtam", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3035", ItemText = "Siniolchu", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3036", ItemText = "Sombari", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3037", ItemText = "Soreng", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3038", ItemText = "Sosing", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3039", ItemText = "Tekhug", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3040", ItemText = "Temi", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3041", ItemText = "Tsetang", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3042", ItemText = "Tsomgo", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3043", ItemText = "Tumlong", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3044", ItemText = "Yangang", ItemType = "cityType"},
new ListItem() { ParentTypeId="30", ItemKey = "3045", ItemText = "Yumtang", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3101", ItemText = "Chennai", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3102", ItemText = "Chidambaram", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3103", ItemText = "Chingleput", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3104", ItemText = "Coimbatore", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3105", ItemText = "Courtallam", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3106", ItemText = "Cuddalore", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3107", ItemText = "Dharmapuri", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3108", ItemText = "Dindigul", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3109", ItemText = "Erode", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3110", ItemText = "Hosur", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3111", ItemText = "Kanchipuram", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3112", ItemText = "Kanyakumari", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3113", ItemText = "Karaikudi", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3114", ItemText = "Karur", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3115", ItemText = "Kodaikanal", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3116", ItemText = "Kovilpatti", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3117", ItemText = "Krishnagiri", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3118", ItemText = "Kumbakonam", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3119", ItemText = "Madurai", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3120", ItemText = "Mayiladuthurai", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3121", ItemText = "Nagapattinam", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3122", ItemText = "Nagarcoil", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3123", ItemText = "Namakkal", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3124", ItemText = "Neyveli", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3125", ItemText = "Nilgiris", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3126", ItemText = "Ooty", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3127", ItemText = "Palani", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3128", ItemText = "Perambalur", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3129", ItemText = "Pollachi", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3130", ItemText = "Pudukkottai", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3131", ItemText = "Rajapalayam", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3132", ItemText = "Ramanathapuram", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3133", ItemText = "Salem", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3134", ItemText = "Sivaganga", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3135", ItemText = "Sivakasi", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3136", ItemText = "Thanjavur", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3137", ItemText = "Theni", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3138", ItemText = "Thoothukudi", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3139", ItemText = "Tiruchirappalli", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3140", ItemText = "Tirunelveli", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3141", ItemText = "Tirupur", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3142", ItemText = "Tiruvallur", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3143", ItemText = "Tiruvannamalai", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3144", ItemText = "Tiruvarur", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3145", ItemText = "Trichy", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3146", ItemText = "Tuticorin", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3147", ItemText = "Vellore", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3148", ItemText = "Villupuram", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3149", ItemText = "Virudhunagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="31", ItemKey = "3150", ItemText = "Yercaud", ItemType = "cityType"},
new ListItem() { ParentTypeId="32", ItemKey = "3201", ItemText = "Agartala", ItemType = "cityType"},
new ListItem() { ParentTypeId="32", ItemKey = "3202", ItemText = "Ambasa", ItemType = "cityType"},
new ListItem() { ParentTypeId="32", ItemKey = "3203", ItemText = "Bampurbari", ItemType = "cityType"},
new ListItem() { ParentTypeId="32", ItemKey = "3204", ItemText = "Belonia", ItemType = "cityType"},
new ListItem() { ParentTypeId="32", ItemKey = "3205", ItemText = "Dhalai", ItemType = "cityType"},
new ListItem() { ParentTypeId="32", ItemKey = "3206", ItemText = "Dharam Nagar", ItemType = "cityType"},
new ListItem() { ParentTypeId="32", ItemKey = "3207", ItemText = "Kailashahar", ItemType = "cityType"},
new ListItem() { ParentTypeId="32", ItemKey = "3208", ItemText = "Kamal Krishnabari", ItemType = "cityType"},
new ListItem() { ParentTypeId="32", ItemKey = "3209", ItemText = "Khopaiyapara", ItemType = "cityType"},
new ListItem() { ParentTypeId="32", ItemKey = "3210", ItemText = "Khowai", ItemType = "cityType"},
new ListItem() { ParentTypeId="32", ItemKey = "3211", ItemText = "Phuldungsei", ItemType = "cityType"},
new ListItem() { ParentTypeId="32", ItemKey = "3212", ItemText = "Radha Kishore Pur", ItemType = "cityType"},
new ListItem() { ParentTypeId="32", ItemKey = "3213", ItemText = "Tripura", ItemType = "cityType"},

            };


            if(App.SELECTED_STATE_ID != "0")
            {
                Items = new ObservableCollection<ListItem>( Items.ToList().Where(x => x.ParentTypeId == App.SELECTED_STATE_ID ));
            }

            RaisePropertyChanged("Items");
        }

        public void BindBloodGroups()
        {
            Items = new ObservableCollection<ListItem> {

                new ListItem() { ItemKey = "1", ItemText = "O+", ItemType = "bloodType" },
                new ListItem() { ItemKey = "2", ItemText = "O-", ItemType = "bloodType" },
                new ListItem() { ItemKey = "3", ItemText = "A+", ItemType = "bloodType" },
                new ListItem() { ItemKey = "4", ItemText = "A-", ItemType = "bloodType" },
                new ListItem() { ItemKey = "5", ItemText = "B+", ItemType = "bloodType" },
                new ListItem() { ItemKey = "6", ItemText = "B-", ItemType = "bloodType" },
                new ListItem() { ItemKey = "7", ItemText = "AB+", ItemType = "bloodType" },
                new ListItem() { ItemKey = "8", ItemText = "AB-", ItemType = "bloodType" }
            };
        }


        public IMvxAsyncCommand<ListItem> ItemTapped => new MvxAsyncCommand<ListItem>(ItemTapped_Handler);
        private async Task ItemTapped_Handler(ListItem item)
        {

            var mvxMessage = new ItemMessage(this, item);
            _mvxMessenger.Publish(mvxMessage);

            await _mvxNavigationService.Navigate<AddPlasmaViewModel>();
        }


        public IMvxAsyncCommand ClosePage => new MvxAsyncCommand(ClosePage_Handler);
        private async Task ClosePage_Handler()
        {
            await _mvxNavigationService.Close(this);
        }
    }
}

